<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ApplicationIcon>assets\numpad.ico</ApplicationIcon>
		<Company>Aryan Jain</Company>
		<Product>TouchpadNumpad</Product>
		<Copyright>© 2026 AryanJ</Copyright>
	</PropertyGroup>

	<ItemGroup>
	  <Folder Include="Profiles\" />
	</ItemGroup>

</Project>